// Original file: src/proto/chat.proto

export enum ResponseStatusEnum {
  SUCCESS  = 'SUCCESS',
  PARTIAL_DATA  = 'PARTIAL_DATA',
  NO_DATA_ERROR  = 'NO_DATA_ERROR',
  BAD_REQUEST_ERROR  = 'BAD_REQUEST_ERROR',
  UNAUTHORIZED_ERROR  = 'UNAUTHORIZED_ERROR',
  FORBIDDEN_ERROR  = 'FORBIDDEN_ERROR',
  NOT_FOUND_ERROR  = 'NOT_FOUND_ERROR',
  NOT_ACCEPTED_ERROR  = 'NOT_ACCEPTED_ERROR',
  ALREADY_EXISTS_ERROR  = 'ALREADY_EXISTS_ERROR',
  INTERNAL_SERVER_ERROR  = 'INTERNAL_SERVER_ERROR',
}
